### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by WellingtonMonteiro** [uhwot/orpheusdl-kkbox#1]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 223, in <module>
    main()
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 176, in main
    module = orpheus.load_module(service_name)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/core.py", line 203, in load_module
    loaded_module = class_(module_controller)
  File "/data/data/com.termux/files/home/orpheusdl/modules/orpheusdl-kkbox/interface.py", line 31, in __init__
    self.session = KkboxAPI(self.exception, settings['kc1_key'], settings['email'], settings['password'], self.tsc.read('kkid'))
  File "/data/data/com.termux/files/home/orpheusdl/modules/orpheusdl-kkbox/kkapi.py", line 41, in __init__
    self.login(email, password)
  File "/data/data/com.termux/files/home/orpheusdl/modules/orpheusdl-kkbox/kkapi.py", line 83, in login
    self.apply_session(resp)
  File "/data/data/com.termux/files/home/orpheusdl/modules/orpheusdl-kkbox/kkapi.py", line 95, in apply_session
    self.lic_content_key = resp['lic_content_key'].encode('ascii')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by uhwot** [comment]
@WellingtonMonteiro hmm, i think they might have changed stuff server-side
hopefully they didn't remove the legacy email/password login, otherwise this is gonna be a mess to fix

**Comment by uhwot** [comment]
@uhwot nvm, they reinforced region restrictions
now your IP address needs to be in one of the supported regions
maybe i'll bypass that later, for now i'll just add an error msg
